### ISSUE TITLE
Update for Gen. VII

### ISSUE THREAD

**Issue by ozv101** [contolini/pokedex#1]
Really like the comprehensive info, but any chance you would update this for Gen. VII or know a good source for the info?

**Comment by contolini** [comment]
Hmmmm I get my data from [PokeAPI](https://github.com/PokeAPI/pokeapi/) and it appears they haven't loaded Gen VII yet (see https://github.com/PokeAPI/pokeapi/issues/112). Thanks for bringing this to my attention, though. I'll look around for a data source.

**Comment by ozv101** [comment]
@contolini yea they haven't updated it to Gen VII. It doesn't look like they will at this point, some asked at the end of 2016.

**Comment by contolini** [comment]
Generation VII species have been added!
