### ISSUE TITLE
Is there any other way to get information apart from pokedex.pokemon(id) ?

### ISSUE THREAD

**Issue by enbermudas** [contolini/pokedex#2]
I would like to do something like this:

`console.log(pokedex.pokemon_abilities(5)); `

because i saw the csv file with that information? My question is: Is that valid or this library does not have this kind o function? If it does not, is there a way to extend it so i can implement thata myself ?

**Comment by tcov189** [comment]
@enbermudez Right now this library doesn't have that functionality. I just made a merge request #3 that will update the current functionality to use an updated version of csvtojson, then once that gets merged I had planned on adding this functionality and also adding that kind of data to the pokemon objects themselves. I am going to start work on that in my forked [repo](https://github.com/tcov189/pokedex)

**Comment by enbermudas** [comment]
@tcov189 Great! I'll be following those changes

**Comment by tcov189** [comment]
@enbermudez Hey just so you know I am going to abandon my fork for this repo in favor for this one https://github.com/jalyna/oakdex-pokedex
